# You can use this file to override parameters for ROS nodes
# After editing this file you can apply the new parameters by running `ros-nodes-restart`

#
# For a list of available parameters and their default values, see: https://docs.fictionlab.pl/raph-rover/documentation/ros-api#parameters
# Note: When removing or commenting out parameters for the controller node, a power cycle of the robot is required for the changes to take effect.
# This is not the case for adding new parameters or changing existing ones.

/**: # Apply to all namespaces
  _: {} # placeholder to prevent empty file error
  # Examples:

  # 1. Changing deceleration and max velocity of the controller node:
  #controller:
  #  ros__parameters:
  #    drivetrain.ackermann_deceleration: 6.0
  #    drivetrain.turn_in_place_deceleration: 9.0
  #    drivetrain.max_wheel_angular_velocity: 20.0

  # 2. Expanding lidar box filter volume, expanding lidar angle filters, lowering scan frequency (600rpm is 10Hz) and enabling interpolated rays of the RPLIDAR node:
  #rplidar:
  #  scan_to_scan_filter_chain:
  #    ros__parameters:
  #      lazy_subscription: true
  #      filter1:
  #        name: box_filter_rover_contour_and_antennas
  #        type: laser_filters/LaserScanBoxFilter
  #        params:
  #          max_x: 0.0
  #          max_y: 0.23
  #          max_z: 0.3
  #          min_x: -0.48
  #          min_y: -0.23
  #          min_z: -0.3
  #          invert: false
  #      filter2:
  #        name: angle_filter_left_motor_cover
  #        type: laser_filters/LaserScanAngularBoundsFilterInPlace
  #        params:
  #          lower_angle: 2.3
  #          upper_angle: 2.8
  #      filter3:
  #        name: angle_filter_right_motor_cover
  #        type: laser_filters/LaserScanAngularBoundsFilterInPlace
  #        params:
  #          lower_angle: 3.4
  #          upper_angle: 3.9
  #  rplidar_node:
  #    ros__parameters:
  #      rpm: 600
  #      interpolated_rays: true

  # Note the above structure: The "scan_to_scan_filter_chain" and "rplidar_node" are separate nodes under the "rplidar" namespace, each with its own parameters.
  # Don't use rplidar/scan_to_scan_filter_chain or rplidar/rplidar_node as the parameter path, as it might not work.

  # 3. Reducing frequency and compression quality of the Oak RGB image:
  #oak:
  #  ros__parameters:
  #    rgb:
  #      fps: 10.0
  #    rgb_compressed:
  #      jpeg_quality: 50