name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v28
    - run: |
        nix build -Lv
        nix fmt -- -c .
